// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEellG856S1hkFQn4ZSB0611i10M75HN8',
    appId: '1:454702418801:web:5cb46d05ddfd74a99e04d0',
    messagingSenderId: '454702418801',
    projectId: 'evently-8d7ce',
    authDomain: 'evently-8d7ce.firebaseapp.com',
    storageBucket: 'evently-8d7ce.firebasestorage.app',
    measurementId: 'G-S3MHPB0MS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBPEJCuFIS3VWSWfjf5BmHggj6FFujmkg',
    appId: '1:454702418801:android:a4571902afc318309e04d0',
    messagingSenderId: '454702418801',
    projectId: 'evently-8d7ce',
    storageBucket: 'evently-8d7ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4fUWpJIJH67ak-tZWe4u8iROOA2TjGBU',
    appId: '1:454702418801:ios:4f447328fabb1b209e04d0',
    messagingSenderId: '454702418801',
    projectId: 'evently-8d7ce',
    storageBucket: 'evently-8d7ce.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );
}
